# Generated by Django 4.0.3 on 2022-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0010_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='process_bpmn_id',
            field=models.IntegerField(null=True),
        ),
    ]
